### ISSUE TITLE
I'm following quickstart on a fresh 4.13 contao intall but can't see any entry in contao Themes. Not sure what I might be missing..

### ISSUE THREAD

**Issue by lebonze** [richardhj/contao-theme-framework#5]

**Comment by lebonze** [comment]
I realise my comment isn't an "issue" sorry

**Comment by richardhj** [comment]
Everything working as expected?

**Comment by lebonze** [comment]
Hi!
Yes I realised /themes should be a new dir at the root :)
I'm struggling with layouts not registering though. I need to dig deeper.
I'm fairly new to contao but loving your idea of themes being more
standardised..
Best
Erwan

**Comment by richardhj** [comment]
The "contao:migrate" or "contao:symlinks" Command is most likely missing. Or you have some typos in the theme.yml

**Comment by lebonze** [comment]
thanks for getting back to me!
I think I'm confused as to where theme.yml gets its templates from. I do
have a fe_page.html5 under /templates/

  _default:
    name: Default layout
    template: fe_page
    rows: 3rw

  other_layout:
    name: Other layout
    template: fe_page_2

**Comment by lebonze** [comment]
It's not picked up under /templates/layouts either
