### ISSUE TITLE
Storing frontend modules within the Theme Framework

### ISSUE THREAD

**Issue by nau7ilus** [richardhj/contao-theme-framework#6]
What's the best way to manage Frontend Modules? I'm considering if it might be a good idea to add the ability to manage these modules to the library?

**Comment by richardhj** [comment]
When contao/contao#5808 gets merged, we finally have a way to use modules without the need to maintain a database. That would be superb indeed 💯 

At the moment, I create a frontend module and use the `{{ '{{insert_module::1}}' }}` or `{{ include() }}` syntax in Twig most of the time.

**Comment by richardhj** [comment]
You can now write `{{ frontend_module(15) }}` or `{{ frontend_module('faqpage', { ... }) }}` to directly embed frontend modules in Twig templates.
